AWSTemplateFormatVersion: 2010-09-09

Description: >
  Bundan sonra
  buraya yazacaklarim
  ben her ne kadar böyle enter
  vura vura da yazsam
  aslinda hepsi tek bir satirda
  yazilmiş olacak.
  
Resources:
  ZehraInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d7a109bf30624c99
      InstanceType: t2.micro
      KeyName: firstkey # key name sonuna .pem yazmıyoruz.
      SecurityGroups: 
        - !Ref ZehraSecGRP
      Tags: 
        - Key: Name
          Value: Zehra-CFN-instance

  ZehraSecGRP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows only SSH connection # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0